// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/proto/helloworld.proto
// Protobuf Java Version: 4.28.2

package com.example.grpc.api;

public interface RPCDateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.api.RPCDateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverDate = 1;</code>
   * @return The serverDate.
   */
  java.lang.String getServerDate();
  /**
   * <code>string serverDate = 1;</code>
   * @return The bytes for serverDate.
   */
  com.google.protobuf.ByteString
      getServerDateBytes();
}
