// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/proto/helloworld.proto
// Protobuf Java Version: 4.28.2

package com.example.grpc.api;

public interface RPCDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.api.RPCDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
